mod support;

use skillator::config::{LibraryConfigCodec, LoadResult, RepositoryConfig, RepositoryConfigCodec};
use skillator::library::{LibrarySnapshot, scan_library};
use skillator::reconcile::{
    Action, Authorization, Outcome, Safety, TargetBusy, execute, plan, prepare_apply,
    prepare_check, prepare_transition,
};
use skillator::target::{Target, observe};
use std::collections::BTreeMap;

const AGENTS_CONTROL: &str = "# Generated by Skillator\n.gitignore\nskillator.yaml\nskills/*\n\n# Exception list for repository tracking\n";

#[cfg(unix)]
#[test]
fn safe_plan_materializes_missing_link_and_control_file() {
    let fixture = Fixture::new("linked");
    let observed = observe(&fixture.target, &fixture.repository, &fixture.library);
    let plan = plan(&fixture.repository, &fixture.library, &observed);
    assert!(
        plan.items()
            .iter()
            .any(|item| item.safety() == Safety::Safe)
    );

    let prepared = prepare_check(&fixture.target, &fixture.repository, &fixture.library).unwrap();
    let result = execute(
        prepared,
        Authorization::SafeOnly,
        &fixture.target,
        &fixture.repository,
        &fixture.library,
    );

    assert!(
        result
            .outcomes()
            .iter()
            .any(|item| item.outcome == Outcome::Applied)
    );
    let link = fixture
        .target
        .root()
        .join(".agents/skills/release-checklist");
    assert_eq!(
        std::fs::read_link(link).unwrap(),
        fixture.skill.canonicalize().unwrap()
    );
    assert_eq!(
        std::fs::read_to_string(fixture.target.root().join(".agents/.gitignore")).unwrap(),
        AGENTS_CONTROL
    );
}

#[cfg(unix)]
#[test]
fn divergent_skill_names_materialize_by_registered_path_in_both_modes() {
    for materialization in ["linked", "copied"] {
        let mut fixture = Fixture::new(materialization);
        let original =
            b"---\nname: Make Bot UI\ndescription: Prepare a release\n---\nOriginal instructions\n";
        std::fs::write(fixture.skill.join("SKILL.md"), original).unwrap();
        fixture.rescan();
        let skill = fixture
            .library
            .source("local/library")
            .unwrap()
            .skill("release-checklist")
            .unwrap();
        assert_eq!(skill.name(), Some("Make Bot UI"));
        assert!(skill.diagnostics().is_empty());
        assert_eq!(skill.warnings().len(), 2);
        let result = execute(
            prepare_check(&fixture.target, &fixture.repository, &fixture.library).unwrap(),
            Authorization::SafeOnly,
            &fixture.target,
            &fixture.repository,
            &fixture.library,
        );
        let destination = fixture
            .target
            .root()
            .join(".agents/skills/release-checklist");
        assert!(
            result.outcomes().iter().any(|outcome| {
                outcome.path == destination && outcome.outcome == Outcome::Applied
            })
        );
        assert_eq!(
            std::fs::read(destination.join("SKILL.md")).unwrap(),
            original
        );
        assert_eq!(
            std::fs::read(fixture.skill.join("SKILL.md")).unwrap(),
            original
        );
    }
}

#[cfg(unix)]
#[test]
fn root_skill_uses_its_safe_metadata_name_as_destination() {
    let mut fixture = Fixture::new("linked");
    let source = fixture.skill.parent().unwrap();
    let original = b"---\nname: Make Bot UI\ndescription: Root skill\n---\n";
    std::fs::write(source.join("SKILL.md"), original).unwrap();
    fixture.rescan();
    let LoadResult::Valid(repository) = RepositoryConfigCodec::parse(
        b"version: 1\nskill_directories:\n  - key: agents\n    path: .agents/skills\nenablements:\n  - directory: agents\n    skill:\n      source: local/library\n      path: .\n    materialization: linked\n",
    ) else {
        panic!("valid root-skill enablement");
    };
    fixture.repository = repository.value().clone();
    let skill = fixture
        .library
        .source("local/library")
        .unwrap()
        .skill(".")
        .unwrap();
    assert!(skill.warnings().len() == 1);
    let result = execute(
        prepare_check(&fixture.target, &fixture.repository, &fixture.library).unwrap(),
        Authorization::SafeOnly,
        &fixture.target,
        &fixture.repository,
        &fixture.library,
    );
    let destination = fixture.target.root().join(".agents/skills/Make Bot UI");
    assert!(
        result
            .outcomes()
            .iter()
            .any(|outcome| { outcome.path == destination && outcome.outcome == Outcome::Applied })
    );
    assert_eq!(
        std::fs::read(destination.join("SKILL.md")).unwrap(),
        original
    );
}

#[cfg(unix)]
#[test]
fn maximum_byte_root_metadata_name_materializes_converts_and_disables() {
    let name = format!("{}x", "é".repeat(127));
    assert_eq!(name.len(), 255);
    for materialization in ["linked", "copied"] {
        let fixture = Fixture::with_identity(materialization, ".", &name);
        exercise_materialization_lifecycle(fixture, &name, materialization);
    }
}

#[cfg(unix)]
#[test]
fn maximum_byte_registered_identity_materializes_converts_and_disables() {
    let name = "r".repeat(255);
    for materialization in ["linked", "copied"] {
        let fixture = Fixture::with_identity(materialization, &name, "Short metadata name");
        exercise_materialization_lifecycle(fixture, &name, materialization);
    }
}

#[cfg(unix)]
fn exercise_materialization_lifecycle(
    mut fixture: Fixture,
    name: &str,
    initial_materialization: &str,
) {
    let destination = fixture.target.root().join(".agents/skills").join(name);
    let original = std::fs::read(fixture.skill.join("SKILL.md")).unwrap();
    let source = fixture.skill.canonicalize().unwrap();
    let alternate = if initial_materialization == "linked" {
        "copied"
    } else {
        "linked"
    };
    for materialization in [initial_materialization, alternate, initial_materialization] {
        fixture.repository = fixture.repository_for(materialization);
        let result = execute(
            prepare_check(&fixture.target, &fixture.repository, &fixture.library).unwrap(),
            Authorization::SafeOnly,
            &fixture.target,
            &fixture.repository,
            &fixture.library,
        );
        assert!(
            result.outcomes().iter().any(|outcome| {
                outcome.path == destination && outcome.outcome == Outcome::Applied
            }),
            "{materialization}: {result:#?}"
        );
        let metadata = std::fs::symlink_metadata(&destination).unwrap();
        if materialization == "linked" {
            assert!(metadata.file_type().is_symlink());
            assert_eq!(std::fs::read_link(&destination).unwrap(), source);
        } else {
            assert!(metadata.is_dir() && !metadata.file_type().is_symlink());
        }
        assert_eq!(
            std::fs::read(destination.join("SKILL.md")).unwrap(),
            original
        );
        assert_eq!(
            std::fs::read(fixture.skill.join("SKILL.md")).unwrap(),
            original
        );
        let observed = observe(&fixture.target, &fixture.repository, &fixture.library);
        assert_eq!(
            observed.enablements().next().unwrap().comparison(),
            skillator::target::Comparison::InSync
        );
        assert!(observed.directories()[0].recovery_artifacts().is_empty());
        support::git(fixture.target.root(), &["add", "-f", ".agents/.gitignore"]);
    }

    let disabled = fixture.repository.with_enablements(Vec::new()).unwrap();
    let result = execute(
        prepare_transition(
            &fixture.target,
            &fixture.repository,
            &disabled,
            &fixture.library,
        )
        .unwrap(),
        Authorization::SafeOnly,
        &fixture.target,
        &disabled,
        &fixture.library,
    );
    assert!(
        result.outcomes().iter().any(|outcome| {
            outcome.path == destination
                && outcome.action == Action::RemoveUnmanaged
                && outcome.outcome == Outcome::Applied
        }),
        "{result:#?}"
    );
    assert!(std::fs::symlink_metadata(&destination).is_err());
    assert_eq!(
        std::fs::read(fixture.skill.join("SKILL.md")).unwrap(),
        original
    );
    let observed = observe(&fixture.target, &disabled, &fixture.library);
    assert!(observed.directories()[0].recovery_artifacts().is_empty());
}

#[cfg(unix)]
#[test]
fn guarded_conflict_requires_all_guarded_authorization() {
    let fixture = Fixture::new("linked");
    let occupant = fixture
        .target
        .root()
        .join(".agents/skills/release-checklist");
    std::fs::create_dir_all(occupant.parent().unwrap()).unwrap();
    std::fs::write(&occupant, "user content").unwrap();
    let observed = observe(&fixture.target, &fixture.repository, &fixture.library);
    let first_plan = plan(&fixture.repository, &fixture.library, &observed);
    assert!(
        first_plan
            .items()
            .iter()
            .any(|item| item.safety() == Safety::Guarded)
    );

    let result = execute(
        prepare_check(&fixture.target, &fixture.repository, &fixture.library).unwrap(),
        Authorization::SafeOnly,
        &fixture.target,
        &fixture.repository,
        &fixture.library,
    );
    assert_eq!(std::fs::read_to_string(&occupant).unwrap(), "user content");
    assert!(
        result
            .outcomes()
            .iter()
            .any(|item| item.outcome == Outcome::NotAuthorized)
    );

    let result = execute(
        prepare_check(&fixture.target, &fixture.repository, &fixture.library).unwrap(),
        Authorization::AllGuarded,
        &fixture.target,
        &fixture.repository,
        &fixture.library,
    );
    assert!(
        result
            .outcomes()
            .iter()
            .any(|item| item.outcome == Outcome::Applied)
    );
    assert!(
        std::fs::symlink_metadata(&occupant)
            .unwrap()
            .file_type()
            .is_symlink()
    );
}

#[test]
fn prepared_plan_holds_an_exclusive_noncreating_target_lock() {
    let fixture = Fixture::new("linked");
    let first = prepare_check(&fixture.target, &fixture.repository, &fixture.library).unwrap();
    let second = prepare_check(&fixture.target, &fixture.repository, &fixture.library);
    std::assert_matches!(second, Err(TargetBusy));
    drop(first);
    assert!(prepare_check(&fixture.target, &fixture.repository, &fixture.library).is_ok());
}

#[test]
fn recovery_restores_one_backup_and_preserves_ambiguous_artifacts() {
    let fixture = Fixture::new("linked");
    let root = fixture.target.root().join(".agents/skills");
    std::fs::create_dir_all(&root).unwrap();
    let encoded = "release-checklist"
        .as_bytes()
        .iter()
        .map(|byte| format!("{byte:02x}"))
        .collect::<String>();
    let backup = root.join(format!(".skillator-backup-1-1-{encoded}"));
    std::fs::write(&backup, "recover me").unwrap();

    let prepared = prepare_apply(&fixture.target, &fixture.repository, &fixture.library).unwrap();
    assert!(!root.join("release-checklist").exists());
    let result = execute(
        prepared,
        Authorization::SafeOnly,
        &fixture.target,
        &fixture.repository,
        &fixture.library,
    );
    assert_eq!(
        std::fs::read_to_string(root.join("release-checklist")).unwrap(),
        "recover me"
    );
    assert!(!backup.exists());
    assert!(result.outcomes().iter().any(|outcome| {
        outcome.action == Action::Recover && outcome.outcome == Outcome::Applied
    }));

    let first = root.join(format!(".skillator-backup-1-2-{encoded}"));
    let second = root.join(format!(".skillator-backup-1-3-{encoded}"));
    std::fs::write(&first, "one").unwrap();
    std::fs::write(&second, "two").unwrap();
    let prepared = prepare_apply(&fixture.target, &fixture.repository, &fixture.library).unwrap();
    assert!(first.exists() && second.exists());
    assert!(
        prepared
            .plan()
            .items()
            .iter()
            .any(|item| { item.action() == Action::Recover && item.safety() == Safety::Blocked })
    );
}

#[test]
fn recovery_blocks_when_destination_becomes_git_protected_after_planning() {
    let fixture = Fixture::new("linked");
    let root = fixture.target.root().join(".agents/skills");
    std::fs::create_dir_all(&root).unwrap();
    let destination = root.join("release-checklist");
    let encoded = "release-checklist"
        .as_bytes()
        .iter()
        .map(|byte| format!("{byte:02x}"))
        .collect::<String>();
    let backup = root.join(format!(".skillator-backup-1-1-{encoded}"));
    std::fs::write(&backup, "recover me").unwrap();
    let prepared = prepare_apply(&fixture.target, &fixture.repository, &fixture.library).unwrap();
    std::fs::write(&destination, "index content").unwrap();
    support::git(
        fixture.target.root(),
        &["add", ".agents/skills/release-checklist"],
    );
    std::fs::remove_file(&destination).unwrap();

    let result = execute(
        prepared,
        Authorization::SafeOnly,
        &fixture.target,
        &fixture.repository,
        &fixture.library,
    );

    assert!(result.outcomes().iter().any(|outcome| {
        outcome.action == Action::Recover && outcome.outcome == Outcome::Blocked
    }));
    assert!(backup.exists());
    assert!(!destination.exists());
}

#[cfg(unix)]
#[test]
fn copied_candidates_preserve_safe_links_and_exclude_git_metadata() {
    let mut fixture = Fixture::new("copied");
    std::fs::create_dir_all(fixture.skill.join("assets")).unwrap();
    std::fs::write(fixture.skill.join("assets/data"), "data").unwrap();
    std::os::unix::fs::symlink("assets/data", fixture.skill.join("data-link")).unwrap();
    std::fs::create_dir_all(fixture.skill.join("assets/.git")).unwrap();
    std::fs::write(fixture.skill.join("assets/.git/secret"), "excluded").unwrap();
    fixture.rescan();
    let result = execute(
        prepare_check(&fixture.target, &fixture.repository, &fixture.library).unwrap(),
        Authorization::SafeOnly,
        &fixture.target,
        &fixture.repository,
        &fixture.library,
    );
    assert!(
        result
            .outcomes()
            .iter()
            .any(|outcome| outcome.action == Action::Copy && outcome.outcome == Outcome::Applied),
        "{result:#?}"
    );
    let destination = fixture
        .target
        .root()
        .join(".agents/skills/release-checklist");
    assert_eq!(
        std::fs::read_link(destination.join("data-link")).unwrap(),
        std::path::PathBuf::from("assets/data")
    );
    assert!(!destination.join("assets/.git").exists());
}

#[cfg(unix)]
#[test]
fn escaping_or_absolute_internal_links_block_copy_without_fallback() {
    let fixture = Fixture::new("copied");
    std::os::unix::fs::symlink("/tmp", fixture.skill.join("escape")).unwrap();
    let observed = observe(&fixture.target, &fixture.repository, &fixture.library);
    let plan = plan(&fixture.repository, &fixture.library, &observed);
    assert!(
        plan.items()
            .iter()
            .any(|item| { item.action() == Action::Replace && item.safety() == Safety::Blocked })
    );
    assert!(
        !fixture
            .target
            .root()
            .join(".agents/skills/release-checklist")
            .exists()
    );
}

#[test]
fn apply_revalidates_destination_without_replanning() {
    let fixture = Fixture::new("linked");
    let prepared = prepare_check(&fixture.target, &fixture.repository, &fixture.library).unwrap();
    let destination = fixture
        .target
        .root()
        .join(".agents/skills/release-checklist");
    std::fs::create_dir_all(destination.parent().unwrap()).unwrap();
    std::fs::write(&destination, "arrived after planning").unwrap();

    let result = execute(
        prepared,
        Authorization::AllGuarded,
        &fixture.target,
        &fixture.repository,
        &fixture.library,
    );
    assert_eq!(
        std::fs::read_to_string(&destination).unwrap(),
        "arrived after planning"
    );
    assert!(
        result
            .outcomes()
            .iter()
            .any(|outcome| { outcome.path == destination && outcome.outcome == Outcome::Blocked })
    );
}

#[test]
fn copied_source_change_after_snapshot_blocks_staged_operation() {
    let fixture = Fixture::new("copied");
    let prepared = prepare_check(&fixture.target, &fixture.repository, &fixture.library).unwrap();
    std::fs::write(fixture.skill.join("new-content"), "changed").unwrap();

    let result = execute(
        prepared,
        Authorization::SafeOnly,
        &fixture.target,
        &fixture.repository,
        &fixture.library,
    );
    assert!(
        result
            .outcomes()
            .iter()
            .any(|outcome| outcome.action == Action::Copy && outcome.outcome == Outcome::Blocked)
    );
    assert!(
        !fixture
            .target
            .root()
            .join(".agents/skills/release-checklist")
            .exists()
    );
}

#[cfg(unix)]
#[test]
fn symlinked_skill_directory_blocks_every_operation_even_with_force() {
    let fixture = Fixture::new("linked");
    let root = fixture.target.root().join(".agents/skills");
    let outside = fixture._home.path().join("outside");
    std::fs::create_dir_all(root.parent().unwrap()).unwrap();
    std::fs::create_dir_all(&outside).unwrap();
    std::os::unix::fs::symlink(&outside, &root).unwrap();

    let prepared = prepare_check(&fixture.target, &fixture.repository, &fixture.library).unwrap();
    assert!(
        prepared
            .plan()
            .items()
            .iter()
            .all(|item| item.safety() == Safety::Blocked)
    );
    let result = execute(
        prepared,
        Authorization::AllGuarded,
        &fixture.target,
        &fixture.repository,
        &fixture.library,
    );

    assert!(
        result
            .outcomes()
            .iter()
            .all(|item| item.outcome == Outcome::Blocked)
    );
    assert_eq!(std::fs::read_dir(outside).unwrap().count(), 0);
}

#[cfg(unix)]
#[test]
fn apply_time_ancestor_symlink_change_cannot_redirect_writes_outside_target() {
    let fixture = Fixture::new("linked");
    let prepared = prepare_check(&fixture.target, &fixture.repository, &fixture.library).unwrap();
    let outside = fixture._home.path().join("outside-race");
    std::fs::create_dir_all(fixture.target.root().join(".agents")).unwrap();
    std::fs::create_dir_all(&outside).unwrap();
    std::os::unix::fs::symlink(&outside, fixture.target.root().join(".agents/skills")).unwrap();

    let result = execute(
        prepared,
        Authorization::AllGuarded,
        &fixture.target,
        &fixture.repository,
        &fixture.library,
    );

    assert_eq!(std::fs::read_dir(outside).unwrap().count(), 0);
    assert!(
        result
            .outcomes()
            .iter()
            .any(|item| { item.action == Action::Link && item.outcome != Outcome::Applied })
    );
}

#[cfg(unix)]
#[test]
fn recovery_never_traverses_a_symlinked_skill_directory() {
    let fixture = Fixture::new("linked");
    let root = fixture.target.root().join(".agents/skills");
    let outside = fixture._home.path().join("outside-recovery");
    std::fs::create_dir_all(root.parent().unwrap()).unwrap();
    std::fs::create_dir_all(&outside).unwrap();
    let encoded = "release-checklist"
        .as_bytes()
        .iter()
        .map(|byte| format!("{byte:02x}"))
        .collect::<String>();
    let artifact = outside.join(format!(".skillator-stage-1-1-{encoded}"));
    std::fs::write(&artifact, "preserve").unwrap();
    std::os::unix::fs::symlink(&outside, &root).unwrap();

    let prepared = prepare_apply(&fixture.target, &fixture.repository, &fixture.library).unwrap();
    drop(prepared);

    assert_eq!(std::fs::read_to_string(artifact).unwrap(), "preserve");
}

#[test]
fn apply_blocks_when_git_protection_changes_after_planning() {
    let fixture = Fixture::new("linked");
    let destination = fixture
        .target
        .root()
        .join(".agents/skills/release-checklist");
    std::fs::create_dir_all(destination.parent().unwrap()).unwrap();
    std::fs::write(&destination, "index placeholder").unwrap();
    let prepared = prepare_check(&fixture.target, &fixture.repository, &fixture.library).unwrap();
    support::git(
        fixture.target.root(),
        &["add", "-N", ".agents/skills/release-checklist"],
    );

    let result = execute(
        prepared,
        Authorization::AllGuarded,
        &fixture.target,
        &fixture.repository,
        &fixture.library,
    );

    assert_eq!(
        std::fs::read_to_string(destination).unwrap(),
        "index placeholder"
    );
    assert!(result.outcomes().iter().any(|item| {
        item.outcome == Outcome::Blocked && item.message.contains("Git status changed")
    }));
}

#[test]
fn staged_deletion_is_git_protected_before_planning_and_force_preserves_content() {
    let fixture = Fixture::new("linked");
    let destination = fixture
        .target
        .root()
        .join(".agents/skills/release-checklist");
    std::fs::create_dir_all(destination.parent().unwrap()).unwrap();
    std::fs::write(&destination, "user content").unwrap();
    support::git(
        fixture.target.root(),
        &["add", ".agents/skills/release-checklist"],
    );
    support::git(fixture.target.root(), &["config", "user.name", "Test User"]);
    support::git(
        fixture.target.root(),
        &["config", "user.email", "test@example.invalid"],
    );
    support::git(fixture.target.root(), &["commit", "-m", "track skill"]);
    support::git(
        fixture.target.root(),
        &["rm", "--cached", ".agents/skills/release-checklist"],
    );

    let prepared = prepare_check(&fixture.target, &fixture.repository, &fixture.library).unwrap();
    assert!(
        prepared
            .plan()
            .items()
            .iter()
            .any(|item| { item.action() == Action::Replace && item.safety() == Safety::Blocked })
    );
    let result = execute(
        prepared,
        Authorization::AllGuarded,
        &fixture.target,
        &fixture.repository,
        &fixture.library,
    );

    assert_eq!(
        std::fs::read_to_string(destination).unwrap(),
        "user content"
    );
    assert!(result.outcomes().iter().any(|outcome| {
        outcome.action == Action::Replace && outcome.outcome == Outcome::Blocked
    }));
}

#[test]
fn staged_deleted_control_file_is_blocked_when_missing_or_modified() {
    for missing in [true, false] {
        let fixture = Fixture::new("linked");
        let root = fixture.target.root().join(".agents/skills");
        std::fs::create_dir_all(&root).unwrap();
        let control = root.parent().unwrap().join(".gitignore");
        std::fs::write(&control, "*\n!.gitignore\n").unwrap();
        support::git(fixture.target.root(), &["add", "-f", ".agents/.gitignore"]);
        support::git(fixture.target.root(), &["config", "user.name", "Test User"]);
        support::git(
            fixture.target.root(),
            &["config", "user.email", "test@example.invalid"],
        );
        support::git(fixture.target.root(), &["commit", "-m", "track control"]);
        support::git(
            fixture.target.root(),
            &["rm", "--cached", ".agents/.gitignore"],
        );
        if missing {
            std::fs::remove_file(&control).unwrap();
        } else {
            std::fs::write(&control, "user rules\n").unwrap();
        }

        let prepared =
            prepare_check(&fixture.target, &fixture.repository, &fixture.library).unwrap();

        assert!(prepared.plan().items().iter().any(|item| {
            item.action() == Action::WriteControlFile && item.safety() == Safety::Blocked
        }));
    }
}

#[cfg(unix)]
#[test]
fn linked_source_replacement_with_a_symlink_is_blocked() {
    let fixture = Fixture::new("linked");
    let prepared = prepare_check(&fixture.target, &fixture.repository, &fixture.library).unwrap();
    let replacement = fixture._home.path().join("replacement-source");
    std::fs::create_dir_all(&replacement).unwrap();
    std::fs::write(
        replacement.join("SKILL.md"),
        "---\nname: release-checklist\ndescription: replacement\n---\n",
    )
    .unwrap();
    std::fs::remove_dir_all(&fixture.skill).unwrap();
    std::os::unix::fs::symlink(&replacement, &fixture.skill).unwrap();

    let result = execute(
        prepared,
        Authorization::SafeOnly,
        &fixture.target,
        &fixture.repository,
        &fixture.library,
    );

    assert!(
        result
            .outcomes()
            .iter()
            .any(|item| item.action == Action::Link && item.outcome == Outcome::Blocked)
    );
    assert!(
        !fixture
            .target
            .root()
            .join(".agents/skills/release-checklist")
            .exists()
    );
}

#[test]
fn linked_source_frontmatter_name_change_after_planning_is_blocked() {
    let mut fixture = Fixture::new("linked");
    std::fs::write(
        fixture.skill.join("SKILL.md"),
        "---\nname: Different Name\ndescription: Prepare a release\n---\n",
    )
    .unwrap();
    fixture.rescan();
    let prepared = prepare_check(&fixture.target, &fixture.repository, &fixture.library).unwrap();
    std::fs::write(
        fixture.skill.join("SKILL.md"),
        "---\nname: renamed-skill\ndescription: Changed\n---\n",
    )
    .unwrap();

    let result = execute(
        prepared,
        Authorization::SafeOnly,
        &fixture.target,
        &fixture.repository,
        &fixture.library,
    );

    assert!(
        result.outcomes().iter().any(|outcome| {
            outcome.action == Action::Link && outcome.outcome == Outcome::Blocked
        })
    );
    assert!(
        !fixture
            .target
            .root()
            .join(".agents/skills/release-checklist")
            .exists()
    );
}

#[cfg(unix)]
#[test]
fn tracked_unmanaged_skills_are_preserved_without_ignore_rules() {
    let fixture = Fixture::new("linked");
    let unmanaged = fixture.target.root().join(".agents/skills/esdiag-release");
    std::fs::create_dir_all(&unmanaged).unwrap();
    std::fs::write(unmanaged.join("SKILL.md"), "repository-owned skill\n").unwrap();
    support::git(
        fixture.target.root(),
        &["add", "-f", ".agents/skills/esdiag-release/SKILL.md"],
    );

    let observed = observe(&fixture.target, &fixture.repository, &fixture.library);
    let plan = plan(&fixture.repository, &fixture.library, &observed);
    assert!(
        !plan
            .items()
            .iter()
            .any(|item| item.action() == Action::RemoveUnmanaged),
        "repository-owned unmanaged skills must not become removal work"
    );

    let result = execute(
        prepare_check(&fixture.target, &fixture.repository, &fixture.library).unwrap(),
        Authorization::SafeOnly,
        &fixture.target,
        &fixture.repository,
        &fixture.library,
    );
    assert!(
        result
            .outcomes()
            .iter()
            .all(|outcome| outcome.outcome != Outcome::Blocked)
    );
    assert!(unmanaged.join("SKILL.md").is_file());
    assert_eq!(
        std::fs::read_to_string(fixture.target.root().join(".agents/.gitignore")).unwrap(),
        AGENTS_CONTROL
    );
}

#[cfg(unix)]
#[test]
fn disabling_an_in_sync_materialization_plans_safe_removal() {
    let fixture = Fixture::new("linked");
    execute(
        prepare_check(&fixture.target, &fixture.repository, &fixture.library).unwrap(),
        Authorization::SafeOnly,
        &fixture.target,
        &fixture.repository,
        &fixture.library,
    );
    support::git(fixture.target.root(), &["add", "-f", ".agents/.gitignore"]);
    let staged = fixture.repository.with_enablements(Vec::new()).unwrap();

    let prepared = prepare_transition(
        &fixture.target,
        &fixture.repository,
        &staged,
        &fixture.library,
    )
    .unwrap();

    assert!(
        prepared.plan().items().iter().any(|item| {
            item.action() == Action::RemoveUnmanaged && item.safety() == Safety::Safe
        })
    );
}

#[cfg(unix)]
#[test]
fn bounded_backup_restores_maximum_byte_payload_without_losing_content() {
    let name = format!("{}x", "é".repeat(127));
    for kind in ["file", "directory", "link"] {
        let mut fixture = Fixture::new("linked");
        fixture.repository = fixture.repository.with_enablements(Vec::new()).unwrap();
        let root = fixture.target.root().join(".agents/skills");
        let backup = root.join(".skillator-backup-1-1");
        std::fs::create_dir_all(&backup).unwrap();
        let payload = backup.join(&name);
        match kind {
            "file" => std::fs::write(&payload, b"original user bytes").unwrap(),
            "directory" => {
                std::fs::create_dir_all(payload.join("assets")).unwrap();
                std::fs::write(payload.join("SKILL.md"), b"original user skill").unwrap();
                std::fs::write(payload.join("assets/data"), b"\0\xfforiginal asset").unwrap();
            }
            "link" => {
                std::os::unix::fs::symlink(fixture.skill.canonicalize().unwrap(), &payload).unwrap()
            }
            _ => unreachable!(),
        }
        let destination = root.join(&name);
        let prepared =
            prepare_apply(&fixture.target, &fixture.repository, &fixture.library).unwrap();
        assert!(std::fs::symlink_metadata(&destination).is_err());
        let observed = observe(&fixture.target, &fixture.repository, &fixture.library);
        assert!(
            observed.directories()[0]
                .recovery_artifacts()
                .contains(&backup)
        );
        let result = execute(
            prepared,
            Authorization::SafeOnly,
            &fixture.target,
            &fixture.repository,
            &fixture.library,
        );
        assert!(
            result.outcomes().iter().any(|outcome| {
                outcome.action == Action::Recover && outcome.outcome == Outcome::Applied
            }),
            "{kind}: {result:#?}"
        );
        match kind {
            "file" => assert_eq!(std::fs::read(&destination).unwrap(), b"original user bytes"),
            "directory" => {
                assert_eq!(
                    std::fs::read(destination.join("SKILL.md")).unwrap(),
                    b"original user skill"
                );
                assert_eq!(
                    std::fs::read(destination.join("assets/data")).unwrap(),
                    b"\0\xfforiginal asset"
                );
            }
            "link" => assert_eq!(
                std::fs::read_link(&destination).unwrap(),
                fixture.skill.canonicalize().unwrap()
            ),
            _ => unreachable!(),
        }
        assert!(!backup.exists());
        let observed = observe(&fixture.target, &fixture.repository, &fixture.library);
        assert!(observed.directories()[0].recovery_artifacts().is_empty());
    }
}

#[test]
fn ambiguous_bounded_backups_are_preserved_even_with_force() {
    let mut fixture = Fixture::new("linked");
    fixture.repository = fixture.repository.with_enablements(Vec::new()).unwrap();
    let root = fixture.target.root().join(".agents/skills");
    let name = "r".repeat(255);
    let first = root.join(".skillator-backup-1-1");
    let second = root.join(".skillator-backup-1-2");
    for (backup, content) in [(&first, "first original"), (&second, "second original")] {
        std::fs::create_dir_all(backup).unwrap();
        std::fs::write(backup.join(&name), content).unwrap();
    }
    let result = execute(
        prepare_apply(&fixture.target, &fixture.repository, &fixture.library).unwrap(),
        Authorization::AllGuarded,
        &fixture.target,
        &fixture.repository,
        &fixture.library,
    );
    for backup in [&first, &second] {
        assert!(
            result.outcomes().iter().any(|outcome| {
                outcome.path == *backup
                    && outcome.action == Action::Recover
                    && outcome.outcome == Outcome::Blocked
            }),
            "{result:#?}"
        );
    }
    assert_eq!(std::fs::read(first.join(&name)).unwrap(), b"first original");
    assert_eq!(
        std::fs::read(second.join(&name)).unwrap(),
        b"second original"
    );
    assert!(std::fs::symlink_metadata(root.join(&name)).is_err());
}

#[test]
fn multiple_child_backup_container_is_not_adopted_or_deleted() {
    let mut fixture = Fixture::new("linked");
    fixture.repository = fixture.repository.with_enablements(Vec::new()).unwrap();
    let root = fixture.target.root().join(".agents/skills");
    let backup = root.join(".skillator-backup-1-1");
    std::fs::create_dir_all(&backup).unwrap();
    std::fs::write(backup.join("release-checklist"), b"original").unwrap();
    std::fs::write(backup.join("unrelated"), b"user notes").unwrap();
    let result = execute(
        prepare_apply(&fixture.target, &fixture.repository, &fixture.library).unwrap(),
        Authorization::AllGuarded,
        &fixture.target,
        &fixture.repository,
        &fixture.library,
    );
    assert!(
        result.outcomes().iter().any(|outcome| {
            outcome.path == backup
                && outcome.action == Action::Recover
                && outcome.outcome == Outcome::Blocked
        }),
        "{result:#?}"
    );
    assert_eq!(
        std::fs::read(backup.join("release-checklist")).unwrap(),
        b"original"
    );
    assert_eq!(
        std::fs::read(backup.join("unrelated")).unwrap(),
        b"user notes"
    );
    assert!(std::fs::symlink_metadata(root.join("release-checklist")).is_err());
    assert!(std::fs::symlink_metadata(root.join("unrelated")).is_err());
}

#[cfg(unix)]
#[test]
fn symlinked_backup_container_never_adopts_or_mutates_outside_content() {
    let mut fixture = Fixture::new("linked");
    fixture.repository = fixture.repository.with_enablements(Vec::new()).unwrap();
    let root = fixture.target.root().join(".agents/skills");
    let outside = fixture._home.path().join("outside");
    std::fs::create_dir_all(&root).unwrap();
    std::fs::create_dir(&outside).unwrap();
    std::fs::write(outside.join("release-checklist"), b"outside original").unwrap();
    let backup = root.join(".skillator-backup-1-1");
    std::os::unix::fs::symlink(&outside, &backup).unwrap();
    let result = execute(
        prepare_apply(&fixture.target, &fixture.repository, &fixture.library).unwrap(),
        Authorization::AllGuarded,
        &fixture.target,
        &fixture.repository,
        &fixture.library,
    );
    assert!(
        result.outcomes().iter().any(|outcome| {
            outcome.path == backup
                && outcome.action == Action::Recover
                && outcome.outcome == Outcome::Blocked
        }),
        "{result:#?}"
    );
    assert_eq!(std::fs::read_link(&backup).unwrap(), outside);
    assert_eq!(
        std::fs::read(outside.join("release-checklist")).unwrap(),
        b"outside original"
    );
    assert!(std::fs::symlink_metadata(root.join("release-checklist")).is_err());
}

#[test]
fn backup_container_changed_after_preparation_preserves_every_child() {
    let mut fixture = Fixture::new("linked");
    fixture.repository = fixture.repository.with_enablements(Vec::new()).unwrap();
    let root = fixture.target.root().join(".agents/skills");
    let backup = root.join(".skillator-backup-1-1");
    std::fs::create_dir_all(&backup).unwrap();
    std::fs::write(backup.join("release-checklist"), b"original").unwrap();
    let prepared = prepare_apply(&fixture.target, &fixture.repository, &fixture.library).unwrap();
    std::fs::write(backup.join("unrelated"), b"concurrent user notes").unwrap();
    let result = execute(
        prepared,
        Authorization::AllGuarded,
        &fixture.target,
        &fixture.repository,
        &fixture.library,
    );
    assert!(
        result.outcomes().iter().any(|outcome| {
            outcome.path == backup
                && outcome.action == Action::Recover
                && outcome.outcome != Outcome::Applied
        }),
        "{result:#?}"
    );
    assert_eq!(
        std::fs::read(backup.join("release-checklist")).unwrap(),
        b"original"
    );
    assert_eq!(
        std::fs::read(backup.join("unrelated")).unwrap(),
        b"concurrent user notes"
    );
    assert!(std::fs::symlink_metadata(root.join("release-checklist")).is_err());
}

#[cfg(unix)]
#[test]
fn backup_container_replaced_by_symlink_after_preparation_is_not_traversed() {
    let mut fixture = Fixture::new("linked");
    fixture.repository = fixture.repository.with_enablements(Vec::new()).unwrap();
    let root = fixture.target.root().join(".agents/skills");
    let backup = root.join(".skillator-backup-1-1");
    std::fs::create_dir_all(&backup).unwrap();
    std::fs::write(backup.join("release-checklist"), b"original").unwrap();
    let prepared = prepare_apply(&fixture.target, &fixture.repository, &fixture.library).unwrap();
    let preserved = fixture._home.path().join("preserved");
    std::fs::rename(&backup, &preserved).unwrap();
    std::os::unix::fs::symlink(&preserved, &backup).unwrap();
    let result = execute(
        prepared,
        Authorization::AllGuarded,
        &fixture.target,
        &fixture.repository,
        &fixture.library,
    );
    assert!(
        result.outcomes().iter().any(|outcome| {
            outcome.path == backup
                && outcome.action == Action::Recover
                && outcome.outcome != Outcome::Applied
        }),
        "{result:#?}"
    );
    assert_eq!(std::fs::read_link(&backup).unwrap(), preserved);
    assert_eq!(
        std::fs::read(preserved.join("release-checklist")).unwrap(),
        b"original"
    );
    assert!(std::fs::symlink_metadata(root.join("release-checklist")).is_err());
}

#[test]
fn unidentified_bounded_stage_remains_manual_recovery_data() {
    let mut fixture = Fixture::new("linked");
    fixture.repository = fixture.repository.with_enablements(Vec::new()).unwrap();
    let root = fixture.target.root().join(".agents/skills");
    let stage = root.join(".skillator-stage-1-1");
    std::fs::create_dir_all(&stage).unwrap();
    std::fs::write(stage.join("SKILL.md"), b"staged skill content").unwrap();
    let result = execute(
        prepare_apply(&fixture.target, &fixture.repository, &fixture.library).unwrap(),
        Authorization::AllGuarded,
        &fixture.target,
        &fixture.repository,
        &fixture.library,
    );
    assert!(
        result.outcomes().iter().any(|outcome| {
            outcome.path == stage
                && outcome.action == Action::Recover
                && outcome.outcome == Outcome::Blocked
        }),
        "{result:#?}"
    );
    assert_eq!(
        std::fs::read(stage.join("SKILL.md")).unwrap(),
        b"staged skill content"
    );
    assert!(std::fs::symlink_metadata(root.join("release-checklist")).is_err());
}

struct Fixture {
    _home: support::TestHome,
    target: Target,
    skill: std::path::PathBuf,
    repository: RepositoryConfig,
    library: LibrarySnapshot,
    registered_path: String,
}

impl Fixture {
    fn new(materialization: &str) -> Self {
        Self::with_identity(materialization, "release-checklist", "release-checklist")
    }

    fn with_identity(materialization: &str, registered_path: &str, metadata_name: &str) -> Self {
        let home = support::TestHome::new();
        let library_root = home.path().join("library");
        let skill = if registered_path == "." {
            library_root.clone()
        } else {
            library_root.join(registered_path)
        };
        std::fs::create_dir_all(&skill).unwrap();
        std::fs::write(
            skill.join("SKILL.md"),
            format!("---\nname: {metadata_name}\ndescription: Prepare a release\n---\n"),
        )
        .unwrap();
        let library_yaml = format!(
            "version: 1\nlocations:\n  - path: {}\n    exclusions: []\n    allow_overlap: false\n    sources:\n      - key: local/library\n        path: .\n        skills:\n          - path: {}\n",
            serde_json::to_string(library_root.to_str().unwrap()).unwrap(),
            serde_json::to_string(registered_path).unwrap()
        );
        let LoadResult::Valid(config) = LibraryConfigCodec::parse(library_yaml.as_bytes()) else {
            panic!("valid Library")
        };
        let library = scan_library(
            config.value(),
            &home.library_config(),
            home.path(),
            &BTreeMap::new(),
        );
        let repository_yaml = format!(
            "version: 1\nskill_directories:\n  - key: agents\n    path: .agents/skills\nenablements:\n  - directory: agents\n    skill:\n      source: local/library\n      path: {}\n    materialization: {materialization}\n",
            serde_json::to_string(registered_path).unwrap()
        );
        let LoadResult::Valid(repository) =
            RepositoryConfigCodec::parse(repository_yaml.as_bytes())
        else {
            panic!("valid Repository")
        };
        let target = Target::select(home.git_repo("target")).unwrap();
        Self {
            _home: home,
            target,
            skill,
            repository: repository.value().clone(),
            library,
            registered_path: registered_path.to_owned(),
        }
    }

    fn repository_for(&self, materialization: &str) -> RepositoryConfig {
        let yaml = format!(
            "version: 1\nskill_directories:\n  - key: agents\n    path: .agents/skills\nenablements:\n  - directory: agents\n    skill:\n      source: local/library\n      path: {}\n    materialization: {materialization}\n",
            serde_json::to_string(&self.registered_path).unwrap()
        );
        let LoadResult::Valid(repository) = RepositoryConfigCodec::parse(yaml.as_bytes()) else {
            panic!("valid Repository")
        };
        repository.value().clone()
    }

    fn rescan(&mut self) {
        let library_root = self._home.path().join("library");
        let library_yaml = format!(
            "version: 1\nlocations:\n  - path: {}\n    exclusions: []\n    allow_overlap: false\n    sources:\n      - key: local/library\n        path: .\n        skills:\n          - path: {}\n",
            serde_json::to_string(library_root.to_str().unwrap()).unwrap(),
            serde_json::to_string(&self.registered_path).unwrap()
        );
        let LoadResult::Valid(config) = LibraryConfigCodec::parse(library_yaml.as_bytes()) else {
            panic!("valid Library")
        };
        self.library = scan_library(
            config.value(),
            &self._home.library_config(),
            self._home.path(),
            &BTreeMap::new(),
        );
    }
}
