mod support;

use skillator::app::{
    AppPaths, LibraryWorkflow, ReportOutcome, ReportStatus, SyncMode, SyncWorkflow, TargetWorkflow,
    UserScopeWorkflow, WorkflowError, WorktreeSyncWorkflow,
};
use skillator::config::{LibraryConfig, LibraryConfigCodec, LoadResult, RepositoryConfigCodec};
use skillator::library::scan_library;
use skillator::reconcile::{Action, Authorization, Safety, prepare_check};
use skillator::target::{RepositorySkillExceptions, Target, observe};
use std::collections::{BTreeMap, BTreeSet};

const AGENTS_CONTROL: &str = "# Generated by Skillator\n.gitignore\nskillator.yaml\nskills/*\n\n# Exception list for repository tracking\n";

#[test]
fn check_reports_safe_work_without_writing_any_target_entry() {
    let fixture = Fixture::new();
    let report = SyncWorkflow::run(&fixture.paths, &fixture.target, SyncMode::Check).unwrap();

    assert_eq!(report.exit_status, 1);
    assert!(
        report
            .changes
            .iter()
            .any(|change| change.outcome == ReportOutcome::WouldApply)
    );
    assert!(!fixture.target.join(".agents/skills").exists());
}

#[cfg(unix)]
#[test]
fn ordinary_sync_applies_safe_work_without_staging_local_controls() {
    let fixture = Fixture::new();
    let report = SyncWorkflow::run(
        &fixture.paths,
        &fixture.target,
        SyncMode::Apply { force: false },
    )
    .unwrap();

    assert_eq!(report.exit_status, 0);
    assert!(
        fixture
            .target
            .join(".agents/skills/release-checklist")
            .symlink_metadata()
            .unwrap()
            .file_type()
            .is_symlink()
    );
    assert!(
        report
            .diagnostics
            .iter()
            .all(|diagnostic| { !diagnostic.message.contains("git add -- .agents/.gitignore") })
    );
}

#[test]
fn sync_without_repository_configuration_is_invalid_input_and_does_not_write() {
    let home = support::TestHome::new();
    let target = home.git_repo("target");
    let paths = AppPaths::new(home.path().to_owned());

    let error = SyncWorkflow::run(&paths, &target, SyncMode::Check).unwrap_err();
    std::assert_matches!(error, WorkflowError::InvalidInput { .. });
    assert!(!target.join(".agents").exists());
}

#[cfg(unix)]
#[test]
fn repeated_sync_converges_without_rewriting_materializations() {
    let fixture = Fixture::new();
    SyncWorkflow::run(
        &fixture.paths,
        &fixture.target,
        SyncMode::Apply { force: false },
    )
    .unwrap();
    let link = fixture.target.join(".agents/skills/release-checklist");
    let before = std::fs::symlink_metadata(&link)
        .unwrap()
        .modified()
        .unwrap();

    let report = SyncWorkflow::run(
        &fixture.paths,
        &fixture.target,
        SyncMode::Apply { force: false },
    )
    .unwrap();

    assert_eq!(report.status, ReportStatus::InSync, "{report:#?}");
    assert_eq!(report.exit_status, 0);
    assert!(report.changes.is_empty());
    assert_eq!(
        std::fs::symlink_metadata(link).unwrap().modified().unwrap(),
        before
    );
}

#[test]
fn active_target_owner_makes_check_busy_without_writes() {
    let fixture = Fixture::new();
    let library_bytes = std::fs::read(fixture.paths.library_config()).unwrap();
    let LoadResult::Valid(library_config) = LibraryConfigCodec::parse(&library_bytes) else {
        panic!("valid Library config")
    };
    let library = scan_library(
        library_config.value(),
        &fixture.paths.library_config(),
        fixture.paths.home(),
        &BTreeMap::new(),
    );
    let repository_bytes = std::fs::read(fixture.target.join(".agents/skillator.yaml")).unwrap();
    let LoadResult::Valid(repository) = RepositoryConfigCodec::parse(&repository_bytes) else {
        panic!("valid Repository config")
    };
    let target = Target::select(&fixture.target).unwrap();
    let _owner = prepare_check(&target, repository.value(), &library).unwrap();

    let error = SyncWorkflow::run(&fixture.paths, &fixture.target, SyncMode::Check).unwrap_err();
    std::assert_matches!(error, WorkflowError::Busy);
    assert!(!fixture.target.join(".agents/skills").exists());
}

#[test]
fn library_inventory_changes_do_not_rewrite_target_references() {
    let fixture = Fixture::new();
    let original_bytes = std::fs::read(fixture.paths.library_config()).unwrap();
    let LoadResult::Valid(original) = LibraryConfigCodec::parse(&original_bytes) else {
        panic!("valid Library config")
    };
    let LoadResult::Valid(staged) = LibraryConfigCodec::parse(
        b"version: 1\nlocations:\n  - path: \"./library\"\n    exclusions: []\n    allow_overlap: false\n    sources:\n      - key: \"local/library\"\n        path: \".\"\n        skills: []\n",
    ) else {
        panic!("valid staged Library config")
    };
    let repository_bytes = std::fs::read(fixture.target.join(".agents/skillator.yaml")).unwrap();
    let LoadResult::Valid(repository) = RepositoryConfigCodec::parse(&repository_bytes) else {
        panic!("valid Repository config")
    };

    let affected =
        LibraryWorkflow::affected_references(original.value(), staged.value(), repository.value());

    assert!(affected.is_empty());
    assert_eq!(
        std::fs::read(fixture.target.join(".agents/skillator.yaml")).unwrap(),
        repository_bytes
    );
}

#[test]
fn stale_target_configuration_blocks_save_before_reconciliation() {
    let fixture = Fixture::new();
    let session = TargetWorkflow::load(&fixture.target).unwrap();
    let prepared =
        TargetWorkflow::prepare_save(&fixture.paths, &session, session.config.clone()).unwrap();
    let path = fixture.target.join(".agents/skillator.yaml");
    std::fs::write(&path, "externally changed\n").unwrap();

    let error =
        TargetWorkflow::commit_save(prepared, skillator::reconcile::Authorization::SafeOnly)
            .unwrap_err();

    std::assert_matches!(error, WorkflowError::InvalidInput { .. });
    assert_eq!(
        std::fs::read_to_string(path).unwrap(),
        "externally changed\n"
    );
    assert!(!fixture.target.join(".agents/skills").exists());
}

#[test]
fn target_save_keeps_clone_local_rules_in_agents_control_file() {
    let fixture = Fixture::new();
    let session = TargetWorkflow::load(&fixture.target).unwrap();
    let prepared =
        TargetWorkflow::prepare_save(&fixture.paths, &session, session.config.clone()).unwrap();

    TargetWorkflow::commit_save(prepared, Authorization::SafeOnly).unwrap();

    assert!(!fixture.target.join(".gitignore").exists());
    assert_eq!(
        std::fs::read_to_string(fixture.target.join(".agents/.gitignore")).unwrap(),
        AGENTS_CONTROL
    );
}

#[test]
fn target_save_preserves_repository_tracking_exceptions() {
    let fixture = Fixture::new();
    let control = fixture.target.join(".agents/.gitignore");
    std::fs::write(
        &control,
        "# Generated by Skillator\nobsolete-rule\n\n# Exception list for repository tracking\n!skills/skillator/\n",
    )
    .unwrap();
    let session = TargetWorkflow::load(&fixture.target).unwrap();
    let prepared =
        TargetWorkflow::prepare_save(&fixture.paths, &session, session.config.clone()).unwrap();

    TargetWorkflow::commit_save(prepared, Authorization::AllGuarded).unwrap();

    assert_eq!(
        std::fs::read_to_string(control).unwrap(),
        format!("{AGENTS_CONTROL}!skills/skillator/\n")
    );
    assert!(!fixture.target.join(".gitignore").exists());
}

#[test]
fn ordinary_sync_prefixes_an_existing_parent_ignore_without_losing_rules() {
    let fixture = Fixture::new();
    let control = fixture.target.join(".agents/.gitignore");
    std::fs::write(&control, "# Existing repository rules\n*.local\n").unwrap();

    let report = SyncWorkflow::run(
        &fixture.paths,
        &fixture.target,
        SyncMode::Apply { force: false },
    )
    .unwrap();

    assert_eq!(report.status, ReportStatus::InSync, "{report:#?}");
    assert_eq!(
        std::fs::read_to_string(control).unwrap(),
        format!("{AGENTS_CONTROL}# Existing repository rules\n*.local\n")
    );
}

#[test]
fn sync_and_save_upgrade_legacy_ignore_files_and_keep_local_controls_ignored() {
    let legacy = "# Generated by skillator.\nskills/.skillator-*\nskills/release-checklist\n";
    for save in [false, true] {
        for existing in [None, Some(legacy)] {
            let fixture = Fixture::new();
            let control = fixture.target.join(".agents/.gitignore");
            if let Some(existing) = existing {
                std::fs::write(&control, existing).unwrap();
            }
            let mut previous = None;
            for _ in 0..2 {
                let report = if save {
                    let session = TargetWorkflow::load(&fixture.target).unwrap();
                    let prepared = TargetWorkflow::prepare_save(
                        &fixture.paths,
                        &session,
                        session.config.clone(),
                    )
                    .unwrap();
                    TargetWorkflow::commit_save(prepared, Authorization::SafeOnly).unwrap()
                } else {
                    SyncWorkflow::run(
                        &fixture.paths,
                        &fixture.target,
                        SyncMode::Apply { force: false },
                    )
                    .unwrap()
                };
                assert_eq!(
                    report.status,
                    ReportStatus::InSync,
                    "save={save}: {report:#?}"
                );
                let content = std::fs::read_to_string(&control).unwrap();
                assert!(content.starts_with(AGENTS_CONTROL), "{content}");
                if let Some(existing) = existing {
                    assert!(
                        content.ends_with(existing),
                        "Existing rules lost: {content}"
                    );
                }
                if let Some(previous) = previous {
                    assert_eq!(
                        content, previous,
                        "Repeated sync/save changed the ignore rules"
                    );
                }
                previous = Some(content);
                let ignored = support::git_output(
                    &fixture.target,
                    &[
                        "check-ignore",
                        ".agents/.gitignore",
                        ".agents/skillator.yaml",
                    ],
                );
                assert_eq!(ignored, ".agents/.gitignore\n.agents/skillator.yaml\n");
                assert!(!fixture.target.join(".gitignore").exists());
            }
        }
    }
}

#[test]
fn target_save_adds_repository_skill_exceptions_without_enablements() {
    let fixture = Fixture::new();
    let repository_skill = fixture.target.join(".agents/skills/project-skill");
    std::fs::create_dir_all(&repository_skill).unwrap();
    std::fs::write(
        repository_skill.join("SKILL.md"),
        "---\nname: project-skill\ndescription: Project-owned instructions\n---\n",
    )
    .unwrap();
    let session = TargetWorkflow::load(&fixture.target).unwrap();
    let original_enablements = session.config.enablements().to_vec();
    let repository_skills = RepositorySkillExceptions::from([(
        "agents".to_owned(),
        BTreeSet::from(["project-skill".to_owned()]),
    )]);
    let prepared = TargetWorkflow::prepare_save_with_repository_skills(
        &fixture.paths,
        &session,
        session.config.clone(),
        repository_skills,
    )
    .unwrap();

    TargetWorkflow::commit_save(prepared, Authorization::SafeOnly).unwrap();

    let saved = TargetWorkflow::load(&fixture.target).unwrap();
    assert_eq!(saved.config.enablements(), original_enablements);
    assert!(
        std::fs::read_to_string(fixture.target.join(".agents/.gitignore"))
            .unwrap()
            .contains("!skills/project-skill/\n")
    );
    assert!(repository_skill.join("SKILL.md").is_file());
}

#[test]
fn tracked_local_target_configuration_blocks_save_with_index_remediation() {
    let fixture = Fixture::new();
    support::git(&fixture.target, &["add", "-f", ".agents/skillator.yaml"]);
    let session = TargetWorkflow::load(&fixture.target).unwrap();
    let prepared =
        TargetWorkflow::prepare_save(&fixture.paths, &session, session.config.clone()).unwrap();

    let error = TargetWorkflow::commit_save(prepared, Authorization::SafeOnly).unwrap_err();

    assert!(
        error
            .to_string()
            .contains("git rm --cached -- .agents/skillator.yaml")
    );
}

#[test]
fn absent_library_keeps_enablements_unresolved_without_creating_a_library() {
    let home = support::TestHome::new();
    let target = home.git_repo("target");
    std::fs::create_dir_all(target.join(".agents")).unwrap();
    std::fs::write(
        target.join(".agents/skillator.yaml"),
        "version: 1\nskill_directories:\n  - key: agents\n    path: .agents/skills\nenablements:\n  - directory: agents\n    skill:\n      source: missing/source\n      path: ghost\n    materialization: linked\n",
    )
    .unwrap();
    let paths = AppPaths::new(home.path().to_owned());

    let report = SyncWorkflow::run(&paths, &target, SyncMode::Check).unwrap();

    assert_eq!(report.exit_status, 1);
    assert!(!home.library_config().exists());
    assert!(!target.join(".agents/skills").exists());
}

#[test]
fn unsupported_library_configuration_is_read_only_invalid_input() {
    let fixture = Fixture::new();
    std::fs::write(
        fixture.paths.library_config(),
        "version: 2\nlocations: []\n",
    )
    .unwrap();

    let error = SyncWorkflow::run(&fixture.paths, &fixture.target, SyncMode::Check).unwrap_err();

    std::assert_matches!(error, WorkflowError::InvalidInput { .. });
    assert!(!fixture.target.join(".agents/skills").exists());
}

#[test]
fn ordinary_sync_partially_applies_safe_work_and_preserves_guarded_occupants() {
    let fixture = Fixture::new();
    let occupant = fixture.target.join(".agents/skills/release-checklist");
    std::fs::create_dir_all(occupant.parent().unwrap()).unwrap();
    std::fs::write(&occupant, "mine").unwrap();

    let report = SyncWorkflow::run(
        &fixture.paths,
        &fixture.target,
        SyncMode::Apply { force: false },
    )
    .unwrap();

    assert_eq!(report.exit_status, 1);
    assert_eq!(std::fs::read_to_string(occupant).unwrap(), "mine");
    assert!(
        report
            .changes
            .iter()
            .any(|change| change.outcome == ReportOutcome::NotAuthorized)
    );
    assert!(fixture.target.join(".agents/.gitignore").exists());
}

#[test]
fn first_run_library_remains_staged_until_confirmed_save() {
    let home = support::TestHome::new();
    let paths = AppPaths::new(home.path().to_owned());
    let session = LibraryWorkflow::load(&paths).unwrap();
    assert!(session.first_run);
    assert!(!home.path().join(".skillator").exists());

    let cancelled = LibraryWorkflow::save(&paths, &session, &session.config, false).unwrap_err();
    std::assert_matches!(cancelled, WorkflowError::Cancelled);
    assert!(!home.path().join(".skillator").exists());

    LibraryWorkflow::save(&paths, &session, &session.config, true).unwrap();
    assert!(home.library_config().exists());
    assert!(home.path().join(".skillator/library").is_dir());
}

#[cfg(unix)]
#[test]
fn repository_configuration_parent_symlink_is_rejected_without_external_writes() {
    let home = support::TestHome::new();
    let target = home.git_repo("target");
    let outside = home.path().join("outside");
    std::fs::create_dir_all(&outside).unwrap();
    std::os::unix::fs::symlink(&outside, target.join(".agents")).unwrap();
    let paths = AppPaths::new(home.path().to_owned());

    let error = SyncWorkflow::run(&paths, &target, SyncMode::Check).unwrap_err();

    std::assert_matches!(error, WorkflowError::InvalidInput { .. });
    assert_eq!(std::fs::read_dir(outside).unwrap().count(), 0);
}

#[test]
fn target_save_restores_a_unique_backup_only_after_configuration_is_saved() {
    let fixture = Fixture::new();
    let root = fixture.target.join(".agents/skills");
    std::fs::create_dir_all(&root).unwrap();
    let encoded = "release-checklist"
        .as_bytes()
        .iter()
        .map(|byte| format!("{byte:02x}"))
        .collect::<String>();
    let backup = root.join(format!(".skillator-backup-1-1-{encoded}"));
    std::fs::write(&backup, "preserved").unwrap();
    let session = TargetWorkflow::load(&fixture.target).unwrap();
    let prepared =
        TargetWorkflow::prepare_save(&fixture.paths, &session, session.config.clone()).unwrap();
    assert!(prepared.plan().items().iter().any(|item| {
        item.action() == skillator::reconcile::Action::Recover
            && item.safety() == skillator::reconcile::Safety::Safe
    }));

    let report =
        TargetWorkflow::commit_save(prepared, skillator::reconcile::Authorization::AllGuarded)
            .unwrap();

    assert_eq!(
        std::fs::read_to_string(root.join("release-checklist")).unwrap(),
        "preserved"
    );
    assert!(!backup.exists());
    assert_eq!(report.exit_status, 1);
    assert!(report.changes.iter().any(|change| {
        change.action == "recover" && change.outcome == skillator::app::ReportOutcome::Applied
    }));
}

#[test]
fn first_run_detects_existing_native_skill_directories_as_recommendations() {
    let home = support::TestHome::new();
    let target = home.git_repo("target");
    std::fs::create_dir_all(target.join(".claude/skills")).unwrap();
    std::fs::create_dir_all(target.join(".cursor/skills")).unwrap();

    let session = TargetWorkflow::load(&target).unwrap();

    assert!(session.first_run);
    assert_eq!(
        session
            .recommendations
            .iter()
            .map(|directory| directory.path().as_str())
            .collect::<Vec<_>>(),
        vec![".claude/skills", ".cursor/skills"]
    );
    assert_eq!(session.config.skill_directories().len(), 1);
}

#[test]
fn first_target_save_creates_required_paths_without_initialization_diagnostics() {
    let home = support::TestHome::new();
    let paths = AppPaths::new(home.path().to_owned());
    let target_root = home.git_repo("target");
    let session = TargetWorkflow::load(&target_root).unwrap();
    let staged = session
        .config
        .with_skill_directories(vec![
            session.config.skill_directories()[0].clone(),
            skillator::config::SkillDirectoryConfig::claude_preset(),
        ])
        .unwrap();
    let library_config = LibraryConfig::first_run();
    let library = scan_library(
        &library_config,
        &paths.library_config(),
        paths.home(),
        &BTreeMap::new(),
    );
    let observed = observe(&session.target, &staged, &library);

    assert!(!target_root.join(".agents").exists());
    for directory in observed.directories() {
        assert!(directory.diagnostics().iter().all(|message| {
            !message.contains("skill folder is not initialized")
                && !message.contains(".gitignore is missing")
        }));
    }

    let prepared = TargetWorkflow::prepare_save(&paths, &session, staged).unwrap();
    for relative in [".agents/skills", ".claude/skills"] {
        assert!(prepared.plan().items().iter().any(|item| {
            item.action() == Action::CreateDirectory
                && item.safety() == Safety::Safe
                && item.path() == session.target.root().join(relative)
        }));
    }
    TargetWorkflow::commit_save(prepared, Authorization::SafeOnly).unwrap();

    assert!(target_root.join(".agents/skillator.yaml").is_file());
    assert!(target_root.join(".agents/skills").is_dir());
    assert!(target_root.join(".claude/skills").is_dir());
    assert_eq!(
        std::fs::read_to_string(target_root.join(".agents/.gitignore")).unwrap(),
        AGENTS_CONTROL
    );
    assert_eq!(
        std::fs::read_to_string(target_root.join(".claude/.gitignore")).unwrap(),
        "# Generated by Skillator\n.gitignore\nskills/*\n\n# Exception list for repository tracking\n"
    );
    assert!(!target_root.join(".gitignore").exists());
}

#[test]
fn first_user_scope_save_creates_desired_state_without_git_control_files() {
    let home = support::TestHome::new();
    let paths = AppPaths::new(home.path().to_owned());
    let session = UserScopeWorkflow::load(&paths).unwrap();

    assert!(session.first_run);
    assert_eq!(session.config.skill_directories()[0].label(), Some("User"));
    assert!(!paths.user_config().exists());

    let prepared =
        UserScopeWorkflow::prepare_save(&paths, &session, session.config.clone()).unwrap();
    assert!(prepared.plan().items().iter().any(|item| {
        item.action() == Action::CreateDirectory
            && item.safety() == Safety::Safe
            && item.path() == home.path().canonicalize().unwrap().join(".agents/skills")
    }));
    assert!(
        prepared
            .plan()
            .items()
            .iter()
            .all(|item| item.action() != Action::WriteControlFile)
    );

    UserScopeWorkflow::commit_save(&paths, prepared, Authorization::SafeOnly).unwrap();

    assert!(paths.user_config().is_file());
    assert!(home.path().join(".agents/skills").is_dir());
    assert!(!home.path().join(".agents/.gitignore").exists());
}

#[cfg(unix)]
#[test]
fn worktree_sync_projects_primary_local_state_and_materializes_skills() {
    let fixture = WorktreeFixture::new();

    let report = WorktreeSyncWorkflow::run(
        &fixture.paths,
        &fixture.linked,
        SyncMode::Apply { force: false },
    )
    .unwrap();

    assert_eq!(report.status, ReportStatus::InSync, "{report:#?}");
    assert_eq!(report.mode, "worktree_sync");
    assert_eq!(
        std::fs::read(fixture.linked.join(".agents/skillator.yaml")).unwrap(),
        std::fs::read(fixture.primary.join(".agents/skillator.yaml")).unwrap()
    );
    assert!(
        std::fs::symlink_metadata(fixture.linked.join(".agents/skills/release-checklist"))
            .unwrap()
            .file_type()
            .is_symlink()
    );
    let registry = std::fs::read_to_string(fixture.paths.target_registry()).unwrap();
    assert!(registry.contains(fixture.linked.to_string_lossy().as_ref()));
}

#[test]
fn worktree_sync_check_does_not_create_destination_configuration() {
    let fixture = WorktreeFixture::new();

    let report =
        WorktreeSyncWorkflow::run(&fixture.paths, &fixture.linked, SyncMode::Check).unwrap();

    assert_eq!(report.status, ReportStatus::NotConverged);
    assert!(report.changes.iter().any(|change| {
        change.path == ".agents/skillator.yaml" && change.outcome == ReportOutcome::WouldApply
    }));
    assert!(report.changes.iter().any(|change| {
        change.action == "register_target" && change.outcome == ReportOutcome::WouldApply
    }));
    assert!(!fixture.linked.join(".agents/skillator.yaml").exists());
    assert!(!fixture.linked.join(".agents/skills").exists());
    assert!(!fixture.paths.target_registry().exists());
}

#[test]
fn worktree_sync_does_not_edit_root_ignore() {
    let fixture = WorktreeFixture::new();
    let root_ignore = fixture.linked.join(".gitignore");
    let before = std::fs::read(&root_ignore).unwrap();

    let report =
        WorktreeSyncWorkflow::run(&fixture.paths, &fixture.linked, SyncMode::Check).unwrap();

    assert_eq!(report.status, ReportStatus::NotConverged);
    assert_eq!(std::fs::read(root_ignore).unwrap(), before);
    assert!(!fixture.linked.join(".agents/skillator.yaml").exists());
}

#[test]
fn worktree_sync_requires_force_for_differing_untracked_configuration() {
    let fixture = WorktreeFixture::new();
    std::fs::create_dir_all(fixture.linked.join(".agents")).unwrap();
    std::fs::write(
        fixture.linked.join(".agents/skillator.yaml"),
        "version: 1\nskill_directories: []\nenablements: []\n",
    )
    .unwrap();
    let before = std::fs::read(fixture.linked.join(".agents/skillator.yaml")).unwrap();

    let guarded = WorktreeSyncWorkflow::run(
        &fixture.paths,
        &fixture.linked,
        SyncMode::Apply { force: false },
    )
    .unwrap();
    assert_eq!(guarded.exit_status, 1);
    assert!(
        guarded
            .changes
            .iter()
            .any(|change| change.outcome == ReportOutcome::WouldRequireForce)
    );
    assert_eq!(
        std::fs::read(fixture.linked.join(".agents/skillator.yaml")).unwrap(),
        before
    );
    assert!(!fixture.paths.target_registry().exists());

    let forced = WorktreeSyncWorkflow::run(
        &fixture.paths,
        &fixture.linked,
        SyncMode::Apply { force: true },
    )
    .unwrap();
    assert_eq!(forced.mode, "worktree_sync_force");
    assert_eq!(forced.status, ReportStatus::InSync, "{forced:#?}");
    assert!(
        forced.changes.iter().any(|change| {
            change.path == ".agents/skillator.yaml" && change.safety == "guarded"
        })
    );
    assert_eq!(
        std::fs::read(fixture.linked.join(".agents/skillator.yaml")).unwrap(),
        std::fs::read(fixture.primary.join(".agents/skillator.yaml")).unwrap()
    );
    assert!(fixture.paths.target_registry().is_file());
}

#[test]
fn worktree_sync_blocks_a_tracked_destination_configuration_even_with_force() {
    let fixture = WorktreeFixture::new();
    std::fs::create_dir_all(fixture.linked.join(".agents")).unwrap();
    let path = fixture.linked.join(".agents/skillator.yaml");
    std::fs::write(
        &path,
        "version: 1\nskill_directories: []\nenablements: []\n",
    )
    .unwrap();
    support::git(&fixture.linked, &["add", "-f", ".agents/skillator.yaml"]);
    let before = std::fs::read(&path).unwrap();

    let report = WorktreeSyncWorkflow::run(
        &fixture.paths,
        &fixture.linked,
        SyncMode::Apply { force: true },
    )
    .unwrap();

    assert_eq!(report.status, ReportStatus::NotConverged);
    assert_eq!(report.exit_status, 1);
    assert!(report.changes.iter().any(|change| {
        change.path == ".agents/skillator.yaml" && change.outcome == ReportOutcome::Blocked
    }));
    assert_eq!(std::fs::read(path).unwrap(), before);
    assert!(!fixture.paths.target_registry().exists());
}

#[cfg(unix)]
#[test]
fn worktree_sync_blocks_an_unreadable_destination_configuration() {
    use std::os::unix::fs::PermissionsExt;

    let fixture = WorktreeFixture::new();
    std::fs::create_dir_all(fixture.linked.join(".agents")).unwrap();
    let path = fixture.linked.join(".agents/skillator.yaml");
    std::fs::write(
        &path,
        "version: 1\nskill_directories: []\nenablements: []\n",
    )
    .unwrap();
    std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o000)).unwrap();

    let result = WorktreeSyncWorkflow::run(
        &fixture.paths,
        &fixture.linked,
        SyncMode::Apply { force: true },
    );
    std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o644)).unwrap();
    let report = result.unwrap();

    assert_eq!(report.status, ReportStatus::NotConverged);
    assert!(
        report
            .diagnostics
            .iter()
            .any(|diagnostic| { diagnostic.message.contains("unreadable") })
    );
    assert!(report.changes.iter().any(|change| {
        change.path == ".agents/skillator.yaml" && change.outcome == ReportOutcome::Blocked
    }));
    assert!(!fixture.paths.target_registry().exists());
}

#[test]
fn worktree_sync_rejects_missing_primary_configuration_without_writes() {
    let fixture = WorktreeFixture::new();
    std::fs::remove_file(fixture.primary.join(".agents/skillator.yaml")).unwrap();

    let error =
        WorktreeSyncWorkflow::run(&fixture.paths, &fixture.linked, SyncMode::Check).unwrap_err();
    assert!(error.to_string().contains("primary worktree configuration"));
    assert!(!fixture.linked.join(".agents").exists());
    assert!(!fixture.paths.target_registry().exists());
}

#[cfg(unix)]
#[test]
fn worktree_sync_keeps_resolvable_skills_when_one_source_is_unavailable() {
    let fixture = WorktreeFixture::new();
    std::fs::write(
        fixture.primary.join(".agents/skillator.yaml"),
        "version: 1\nskill_directories:\n  - key: agents\n    path: .agents/skills\nenablements:\n  - directory: agents\n    skill:\n      source: local/library\n      path: release-checklist\n    materialization: linked\n  - directory: agents\n    skill:\n      source: missing/source\n      path: ghost\n    materialization: linked\n",
    )
    .unwrap();

    let report = WorktreeSyncWorkflow::run(
        &fixture.paths,
        &fixture.linked,
        SyncMode::Apply { force: false },
    )
    .unwrap();

    assert_eq!(report.status, ReportStatus::NotConverged);
    assert!(
        std::fs::symlink_metadata(fixture.linked.join(".agents/skills/release-checklist"))
            .unwrap()
            .file_type()
            .is_symlink()
    );
    assert!(report.diagnostics.iter().any(|diagnostic| {
        diagnostic.code == "final_enablement_state" || diagnostic.message.contains("unavailable")
    }));
}

struct Fixture {
    _home: support::TestHome,
    paths: AppPaths,
    target: std::path::PathBuf,
}

impl Fixture {
    fn new() -> Self {
        let home = support::TestHome::new();
        let library = home.path().join(".skillator/library/release-checklist");
        std::fs::create_dir_all(&library).unwrap();
        std::fs::write(
            library.join("SKILL.md"),
            "---\nname: release-checklist\ndescription: Prepare a release\n---\n",
        )
        .unwrap();
        std::fs::write(
            home.library_config(),
            "version: 1\nlocations:\n  - path: \"./library\"\n    exclusions: []\n    allow_overlap: false\n    sources:\n      - key: \"local/library\"\n        path: \".\"\n        skills:\n          - path: \"release-checklist\"\n",
        )
        .unwrap();
        let target = home.git_repo("target");
        std::fs::create_dir_all(target.join(".agents")).unwrap();
        std::fs::write(
            target.join(".agents/skillator.yaml"),
            "version: 1\nskill_directories:\n  - key: \"agents\"\n    path: \".agents/skills\"\nenablements:\n  - directory: \"agents\"\n    skill:\n      source: \"local/library\"\n      path: \"release-checklist\"\n    materialization: \"linked\"\n",
        )
        .unwrap();
        Self {
            paths: AppPaths::new(home.path().to_owned()),
            _home: home,
            target,
        }
    }
}

#[cfg(unix)]
struct WorktreeFixture {
    _home: support::TestHome,
    paths: AppPaths,
    primary: std::path::PathBuf,
    linked: std::path::PathBuf,
}

#[cfg(unix)]
impl WorktreeFixture {
    fn new() -> Self {
        let home = support::TestHome::new();
        let library = home.path().join("library/release-checklist");
        std::fs::create_dir_all(&library).unwrap();
        std::fs::write(
            library.join("SKILL.md"),
            "---\nname: release-checklist\ndescription: Prepare a release\n---\n",
        )
        .unwrap();
        std::fs::create_dir_all(home.library_config().parent().unwrap()).unwrap();
        std::fs::write(
            home.library_config(),
            format!(
                "version: 1\nlocations:\n  - path: {}\n    exclusions: []\n    allow_overlap: false\n",
                serde_json::to_string(library.parent().unwrap().to_str().unwrap()).unwrap()
            ),
        )
        .unwrap();

        let primary = home.git_repo("primary");
        std::fs::write(primary.join(".gitignore"), "/target\n").unwrap();
        support::git(&primary, &["add", ".gitignore"]);
        support::git(&primary, &["config", "user.name", "Test User"]);
        support::git(&primary, &["config", "user.email", "test@example.invalid"]);
        support::git(&primary, &["commit", "-m", "seed worktree"]);

        let linked = home.path().join("linked");
        let linked_arg = linked.to_str().unwrap();
        support::git(
            &primary,
            &["worktree", "add", "--quiet", linked_arg, "-b", "linked"],
        );
        std::fs::create_dir_all(primary.join(".agents")).unwrap();
        std::fs::write(
            primary.join(".agents/skillator.yaml"),
            "version: 1\nskill_directories:\n  - key: agents\n    path: .agents/skills\nenablements:\n  - directory: agents\n    skill:\n      source: local/library\n      path: release-checklist\n    materialization: linked\n",
        )
        .unwrap();

        Self {
            paths: AppPaths::new(home.path().to_owned()),
            _home: home,
            primary,
            linked,
        }
    }
}
